repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: rrap
  description: Raw Reads Analysis Pipeline - taxonomic and functional analysis of raw reads.
  author: Timothy Rozday
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
