---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "krona_ktimporttext"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::krona=2.8.1"
